# DIFFERENT TYPES OF ARRAY INITIALIZATION

# 1.Zero Matrix

In [1]:
import numpy as np
print(np.zeros(3))

[0. 0. 0.]


In [2]:
print(np.zeros((3,3)))

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [3]:
print(np.zeros((3,2,2),dtype='int32'))

[[[0 0]
  [0 0]]

 [[0 0]
  [0 0]]

 [[0 0]
  [0 0]]]


# Ones Matrix

In [4]:
print(np.ones(3))

[1. 1. 1.]


In [5]:
print(np.ones((3,3)))

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [6]:
print(np.ones((3,2,2)))

[[[1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]]]


# Scalar Matrix

In [7]:
sm=np.full((3,3),27)
print(sm)

[[27 27 27]
 [27 27 27]
 [27 27 27]]


In [8]:
np.full_like(sm,3)

array([[3, 3, 3],
       [3, 3, 3],
       [3, 3, 3]])

# Random Element Matrix 

In [9]:
np.random.rand(4,4)

array([[0.59633085, 0.00815196, 0.91377562, 0.40038473],
       [0.76729629, 0.616157  , 0.57383113, 0.49118812],
       [0.59947105, 0.49636107, 0.65674519, 0.58679541],
       [0.17715545, 0.91095183, 0.37203493, 0.42029593]])

In [10]:
np.random.randint(1,9,size=(3,3))

array([[5, 4, 7],
       [5, 4, 5],
       [2, 2, 7]])

# Identity Matrix

In [11]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

# Repeatind and replacing

In [12]:
c=np.array([5,6,7])
print(np.repeat(c,3))

[5 5 5 6 6 6 7 7 7]


In [13]:
d=np.array([[5,6,7]])
print(d)

[[5 6 7]]


In [14]:
print(np.repeat(d,3,axis=0))

[[5 6 7]
 [5 6 7]
 [5 6 7]]


In [15]:
print(np.repeat(d,3,axis=1))

[[5 5 5 6 6 6 7 7 7]]


In [16]:
sample1=np.zeros((5,5),dtype='int32')
sample2=np.ones((3,3),dtype='int32')
print(sample1,'\n\n')
print(sample2)

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]] 


[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [17]:
# replacing syntax:array1[row-range,col-range]=array2
sample1[1:4,1:4]=sample2
print(sample1)

[[0 0 0 0 0]
 [0 1 1 1 0]
 [0 1 1 1 0]
 [0 1 1 1 0]
 [0 0 0 0 0]]


# Copying an array

In [18]:
#using = operator
c1=np.array([1,2,3])
print(c1)
c2=c1
c2[0]=4
print(c1)
print(c2)

[1 2 3]
[4 2 3]
[4 2 3]


In [19]:
#using copy function
c1=np.array([1,2,3])
print(c1)
c2=c1.copy()
c2[0]=4
print(c1)
print(c2)

[1 2 3]
[1 2 3]
[4 2 3]


# MATHEMATICAL OPERATIONS ON ARRAY

# Single dimensional array

In [20]:
matharr=np.array([2,4,6,8])
print(matharr,'\n\n')
print(matharr+2,'\n\n')
print(matharr-2,'\n\n')
print(matharr*2,'\n\n')
print(matharr/2,'\n\n')
print(matharr**2,'\n\n')


[2 4 6 8] 


[ 4  6  8 10] 


[0 2 4 6] 


[ 4  8 12 16] 


[1. 2. 3. 4.] 


[ 4 16 36 64] 




In [21]:
np.sin(matharr)

array([ 0.90929743, -0.7568025 , -0.2794155 ,  0.98935825])

In [22]:
np.cos(matharr)

array([-0.41614684, -0.65364362,  0.96017029, -0.14550003])

# Multi-dimensional array

In [23]:
x1=np.full((3,3),3)
x2=np.ones((3,3),dtype='int32')
print(x1,'\n')

[[3 3 3]
 [3 3 3]
 [3 3 3]] 



In [24]:
print(x2,'\n')

[[1 1 1]
 [1 1 1]
 [1 1 1]] 



In [25]:
print(x1+x2,'\n')


[[4 4 4]
 [4 4 4]
 [4 4 4]] 



In [26]:
print(x1-x2,'\n')

[[2 2 2]
 [2 2 2]
 [2 2 2]] 



In [27]:
print(x1*x2,'\n')

[[3 3 3]
 [3 3 3]
 [3 3 3]] 



In [28]:
print(np.matmul(x1,x2),'\n')

[[9 9 9]
 [9 9 9]
 [9 9 9]] 

