In [1]:
import pandas as pd
from sklearn.naive_bayes import MultinomialNB
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.pipeline import Pipeline
from sklearn.model_selection import train_test_split

In [2]:
df=pd.read_csv('spam.csv')
df

Category                                            Message
0         ham  Go until jurong point, crazy.. Available only ...
1         ham                      Ok lar... Joking wif u oni...
2        spam  Free entry in 2 a wkly comp to win FA Cup fina...
3         ham  U dun say so early hor... U c already then say...
4         ham  Nah I don't think he goes to usf, he lives aro...
...       ...                                                ...
5567     spam  This is the 2nd time we have tried 2 contact u...
5568      ham               Will ü b going to esplanade fr home?
5569      ham  Pity, * was in mood for that. So...any other s...
5570      ham  The guy did some bitching but I acted like i'd...
5571      ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [3]:
df.describe()

Category                 Message
count      5572                    5572
unique        2                    5157
top         ham  Sorry, I'll call later
freq       4825                      30

In [4]:
df.groupby('Category').describe()

Message                                                            \
           count unique                                                top   
Category                                                                     
ham         4825   4516                             Sorry, I'll call later   
spam         747    641  Please call our customer service representativ...   

               
         freq  
Category       
ham        30  
spam        4

In [5]:
clf=Pipeline([('vectorizer',CountVectorizer()),('nb',MultinomialNB())])

In [6]:
df['spam']=df['Category'].apply(lambda x:1 if x=='spam' else 0)
df

Category                                            Message  spam
0         ham  Go until jurong point, crazy.. Available only ...     0
1         ham                      Ok lar... Joking wif u oni...     0
2        spam  Free entry in 2 a wkly comp to win FA Cup fina...     1
3         ham  U dun say so early hor... U c already then say...     0
4         ham  Nah I don't think he goes to usf, he lives aro...     0
...       ...                                                ...   ...
5567     spam  This is the 2nd time we have tried 2 contact u...     1
5568      ham               Will ü b going to esplanade fr home?     0
5569      ham  Pity, * was in mood for that. So...any other s...     0
5570      ham  The guy did some bitching but I acted like i'd...     0
5571      ham                         Rofl. Its true to its name     0

[5572 rows x 3 columns]

In [7]:
clf.fit(df.Message,df.spam)

Pipeline(memory=None,
         steps=[('vectorizer',
                 CountVectorizer(analyzer='word', binary=False,
                                 decode_error='strict',
                                 dtype=<class 'numpy.int64'>, encoding='utf-8',
                                 input='content', lowercase=True, max_df=1.0,
                                 max_features=None, min_df=1,
                                 ngram_range=(1, 1), preprocessor=None,
                                 stop_words=None, strip_accents=None,
                                 token_pattern='(?u)\\b\\w\\w+\\b',
                                 tokenizer=None, vocabulary=None)),
                ('nb',
                 MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True))],
         verbose=False)

In [8]:
clf.predict(df.Message)

array([0, 0, 1, ..., 0, 0, 0], dtype=int64)

In [9]:
df2=pd.read_csv('spamcheck.csv')
df2

SPAM MSG
0  Pay for limited years & get covered for entire...
1  Get your Annual Preventive Health Check-Up And...
2   Hurry! 60 full body Lab Tests @ just Rs.750 Now.
3       Loans upto 30 lac can be approved in seconds
4              left my laptop at home can you get me
5                                            ok sure
6                                R U going out today
7               Will u b going to esplanade fr home?

In [10]:
clf.predict(df2['SPAM MSG'])

array([0, 0, 0, 0, 0, 0, 0, 0], dtype=int64)

In [11]:
clf.predict(['Ok lar... Joking wif u oni...'])

array([0], dtype=int64)

In [12]:
v=CountVectorizer()

In [13]:
XTR,XTS,YTR,YTS=train_test_split(df.Message,df.spam)

In [14]:
XTRtrans=v.fit_transform(XTR.values)

In [15]:
XTRtrans.toarray()[:2]

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [16]:
model=MultinomialNB()

In [17]:
model.fit(XTRtrans,YTR)

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [18]:
XTStrans=v.transform(XTS)

In [20]:
model.predict(XTStrans)

array([0, 0, 0, ..., 0, 1, 0], dtype=int64)

In [22]:
model.score(XTStrans,YTS)

0.9849246231155779

In [24]:
df2

SPAM MSG
0  Pay for limited years & get covered for entire...
1  Get your Annual Preventive Health Check-Up And...
2   Hurry! 60 full body Lab Tests @ just Rs.750 Now.
3       Loans upto 30 lac can be approved in seconds
4              left my laptop at home can you get me
5                                            ok sure
6                                R U going out today
7               Will u b going to esplanade fr home?

In [62]:
email=df2.values[5]
email

array(['ok sure'], dtype=object)

In [63]:
emailstrans=v.transform(email)

In [64]:
model.predict(emailstrans)

array([0], dtype=int64)